### ISSUE TITLE
English Version Dataset 

### ISSUE THREAD

**Issue by luomancs** [lwgkzl/MedDG#3]
Hi, 

I am looking for English version dataset, however, from the google drive, I only saw Chinese version. Could you please release the English version as well? 

Thank you

**Comment by daveynkanta** [comment]
I am looking for the same English version. Please share if you get it

**Comment by lwgkzl** [comment]
> Hi,
> 
> I am looking for English version dataset, however, from the google drive, I only saw Chinese version. Could you please release the English version as well?
> 
> Thank you

We only have the Chinese version at present. I'm really sorry
