### ISSUE TITLE
Entity Annotation

### ISSUE THREAD

**Issue by deekshaVarshney** [lwgkzl/MedDG#4]
You have mentioned in your dataset that "First, a part of the dataset is manually annotated, and then an automatic program is designed to label the rest of the dataset." and then you have said "We then develop a program to label the rest conversation automatically. The program consists of regex rules for each item to cover all human-labeled data, and apply these rules to label other dialogues."

Can you please share the script for these regex rules?

**Comment by lwgkzl** [comment]
Thank you very much for your attention to our work.  I am very sorry that the annotation rules are not open source for some reasons.
