### ISSUE TITLE
Topic Prediction

### ISSUE THREAD

**Issue by deekshaVarshney** [lwgkzl/MedDG#5]
In the topic prediction folder, there are several scripts like baseline.py bert.py, baseline_five_class.py and bert_graph.py. Can you explain what each file is doing ?

Also, if you could tell how can we get the predictions of topic and classes for the test set from this script?

**Comment by lwgkzl** [comment]
> In the topic prediction folder, there are several scripts like baseline.py bert.py, baseline_five_class.py and bert_graph.py. Can you explain what each file is doing ?
> 
> Also, if you could tell how can we get the predictions of topic and classes for the test set from this script?

It's a complicated explanation, you need to read allenlp's documentation(0.9.0) for its usage, thanks.
